name: dart_elf
version: 1.0.0
description: A pure Dart library for parsing ELF binaries.
homepage: https://github.com/libdbm/dart-elf
repository: https://github.com/libdbm/dart-elf
issue_tracker: https://github.com/libdbm/dart-elf/issues

environment:
  sdk: ^3.0.5

dependencies:
  args: ^2.4.2
  sprintf: ^7.0.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
